#!/bin/bash 
mkdir /etc/e2guardian/lists/blacklists/ -p

KRUG=0
while [  $KRUG -lt 3 ]; do
case $KRUG in
0)
  PRE='mkdir -p /etc/e2guardian/lists/blacklists/'
  POS=''
  ;;
1)
  PRE='touch /etc/e2guardian/lists/blacklists/'
  POS='/urls'
  ;;
2)
  PRE='touch /etc/e2guardian/lists/blacklists/'
  POS='/domains'
  ;;
esac

eval "$PRE"_custom"$POS"
eval "$PRE"abortion"$POS"
eval "$PRE"adult"$POS"
eval "$PRE"aggressive"$POS"
eval "$PRE"alcohol"$POS"
eval "$PRE"antispyware"$POS"
eval "$PRE"arjel"$POS"
eval "$PRE"artnudes"$POS"
eval "$PRE"associations_religieuses"$POS"
eval "$PRE"astrology"$POS"
eval "$PRE"audio-video"$POS"
eval "$PRE"bank"$POS"
eval "$PRE"banking"$POS"
eval "$PRE"beerliquorinfo"$POS"
eval "$PRE"beerliquorsale"$POS"
eval "$PRE"bitcoin"$POS"
eval "$PRE"blog"$POS"
eval "$PRE"books"$POS"
eval "$PRE"catalogue-biu-toulouse"$POS"
eval "$PRE"celebrity"$POS"
eval "$PRE"cellphones"$POS"
eval "$PRE"chat"$POS"
eval "$PRE"child"$POS"
eval "$PRE"childcare"$POS"
eval "$PRE"cleaning"$POS"
eval "$PRE"clothing"$POS"
eval "$PRE"contraception"$POS"
eval "$PRE"cooking"$POS"
eval "$PRE"culinary"$POS"
eval "$PRE"dating"$POS"
eval "$PRE"ddos"$POS"
eval "$PRE"desktopsillies"$POS"
eval "$PRE"dialers"$POS"
eval "$PRE"download"$POS"
eval "$PRE"drugs"$POS"
eval "$PRE"ecommerce"$POS"
eval "$PRE"educational_games"$POS"
eval "$PRE"entertainment"$POS"
eval "$PRE"filehosting"$POS"
eval "$PRE"filesharing"$POS"
eval "$PRE"financial"$POS"
eval "$PRE"forums"$POS"
eval "$PRE"frencheducation"$POS"
eval "$PRE"gambling"$POS"
eval "$PRE"games"$POS"
eval "$PRE"gardening"$POS"
eval "$PRE"good"$POS"
eval "$PRE"government"$POS"
eval "$PRE"guns"$POS"
eval "$PRE"hacking"$POS"
eval "$PRE"homerepair"$POS"
eval "$PRE"humor"$POS"
eval "$PRE"hunting"$POS"
eval "$PRE"hygiene"$POS"
eval "$PRE"indisponible"$POS"
eval "$PRE"instantmessaging"$POS"
eval "$PRE"jewelry"$POS"
eval "$PRE"jobsearch"$POS"
eval "$PRE"jstor"$POS"
eval "$PRE"kidstimewasting"$POS"
eval "$PRE"lingerie"$POS"
eval "$PRE"liste_blanche"$POS"
eval "$PRE"local"$POS"
eval "$PRE"magazines"$POS"
eval "$PRE"mail"$POS"
eval "$PRE"malware"$POS"
eval "$PRE"manga"$POS"
eval "$PRE"marketingware"$POS"
eval "$PRE"medical"$POS"
eval "$PRE"mixed_adult"$POS"
eval "$PRE"mobile-phone"$POS"
eval "$PRE"naturism"$POS"
eval "$PRE"news"$POS"
eval "$PRE"onlineauctions"$POS"
eval "$PRE"onlinegames"$POS"
eval "$PRE"onlinepayment"$POS"
eval "$PRE"personalfinance"$POS"
eval "$PRE"pets"$POS"
eval "$PRE"phishing"$POS"
eval "$PRE"porn"$POS"
eval "$PRE"press"$POS"
eval "$PRE"proxy"$POS"
eval "$PRE"publicite"$POS"
eval "$PRE"radio"$POS"
eval "$PRE"reaffected"$POS"
eval "$PRE"redirector"$POS"
eval "$PRE"religion"$POS"
eval "$PRE"remote-control"$POS"
eval "$PRE"ringtones"$POS"
eval "$PRE"searchengines"$POS"
eval "$PRE"sect"$POS"
eval "$PRE"sexuality"$POS"
eval "$PRE"sexualityeducation"$POS"
eval "$PRE"shopping"$POS"
eval "$PRE"shortener"$POS"
eval "$PRE"socialnetworking"$POS"
eval "$PRE"social_networks"$POS"
eval "$PRE"special"$POS"
eval "$PRE"sportnews"$POS"
eval "$PRE"sports"$POS"
eval "$PRE"spyware"$POS"
eval "$PRE"tobacco"$POS"
eval "$PRE"translation"$POS"
eval "$PRE"update"$POS"
eval "$PRE"updatesites"$POS"
eval "$PRE"vacation"$POS"
eval "$PRE"verisign"$POS"
eval "$PRE"violence"$POS"
eval "$PRE"virusinfected"$POS"
eval "$PRE"warez"$POS"
eval "$PRE"weapons"$POS"
eval "$PRE"weather"$POS"
eval "$PRE"webmail"$POS"
eval "$PRE"whitelist"$POS"

let KRUG=KRUG+1
done

